name: Kodi Addon-Check

on: [push, pull_request, workflow_dispatch]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: dudanov/action-kodi-addon-checker@fixes-2025-07-21
      with:
        kodi-version: nexus
        is-pr: false
        addon-id: plugin.audio.zophar
