name: Release

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: plugin

      - name: Package source code including submodules
        uses: qmonnet/git-archive-all-action@v1
        with:
          base-repo: plugin
          output-files: plugin.audio.zophar.zip
          prefix: plugin.audio.zophar/

      - uses: mavrosxristoforos/get-xml-info@2.0
        id: get_version
        with:
          xml-file: plugin/addon.xml
          xpath: /addon/@version

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.info }}
          files: plugin.audio.zophar.zip
